typography_spectrum: 0.15897594299167395
color:
  brandColors: []
  brandStrength: 0.5625
  lightness: 0.37353461398743093
  saturation: 0.673302135663107
  rhythmicContrast: 0.00960685103200376
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.29927
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Xiyang Chen
  email: settinghead@gmail.com
  url: settinghead.info
name: settinghead
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
description: ''
purpose: []
