name: settinghead
favicon: null
layout_spectrum: 0.29927
typography_spectrum: 0.15897594299167395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5625
  lightness: 0.37353461398743093
  saturation: 0.673302135663107
  rhythmicContrast: 0.00960685103200376
purpose: []
